#logging:
#  level:
#    org:
#      springframework: debug
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#server:
#  servlet:
#    contextPath: /springfox
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false